name: Leap Stories
favicon: null
layout_spectrum: 0.959066323004663
typography_spectrum: 0.06281700124964118
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9064019527286291
  lightness: 0.4331751470454037
  saturation: 0.504244102165103
  rhythmicContrast: 0.13381461915560067
purpose: []
